spring:
  application:
    name: discovery-service

server:
  port: 8761

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    service-url:
      defaultZone: "${EUREKA_DEFAULT_ZONE:http://localhost:8761/eureka}"