spring:
  application:
    name: song-service
  datasource:
    name: "${RESOURCE_DB_NAME:song-db}"
    username: "${SPRING_DATASOURCE_USERNAME:postgres}"
    password: "${SPRING_DATASOURCE_PASSWORD:postgres}"
    url: "${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/song-db}"

server:
  port: 6868