spring:
  application:
    name: resource-service
  datasource:
    name: "${RESOURCE_DB_NAME:resource-db}"
    username: "${SPRING_DATASOURCE_USERNAME:postgres}"
    password: "${SPRING_DATASOURCE_PASSWORD:postgres}"
    url: "${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/resource-db}"

server:
  port: 6969

external:
  services:
    song-service-host: "${SONG_SERVICE_URL:http://localhost:6868}"
